### ISSUE TITLE
ADMIN_PASSWORD set, can't sign in anyway

### ISSUE THREAD

**Issue by tacotexmex** [minetest-go/mtui#176]
I remember being asked to create an admin password. Immediately lost it, but thought that it could be overridden with said environment variable. Is this not intended? Otherwise, where are passwords stored and how do I reset it?

**Comment by BuckarooBanzay** [comment]
The `ADMIN_PASSWORD` only works if no existing user is found.
In your case you can remove all auth entries and do the "onboarding" again.

Either with a sql query:
```sh
sqlite3 auth.sqlite "delete from auth"
```

Or alternatively just remove the auth database directly (stop the ui-app for that):
```sh
rm auth.sqlite*
```

I'm curious: there is currently no proper readme how to set this up and i haven't "release" this officially, how did you stumble on this and how/where do you plan to use it? :thinking:

**Comment by BuckarooBanzay** [comment]
inactive, closing
