### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by nonfreegithub** [minetest-go/mtui#209]
It works fine with sqlite, but dont work when I test it in pgsql worlds

Is pgsql supported?

**Comment by BuckarooBanzay** [comment]
Postgres is supported and i'm using in on 2 servers without issues.
This is the `world.mt` for the pandorabox server:

```
gameid = minetest
backend = postgresql
creative_mode = false
enable_damage = true
player_backend = postgresql

pgsql_connection = host=/var/run/postgresql user=postgres password=enter dbname=postgres
pgsql_auth_connection = host=/var/run/postgresql user=postgres password=enter dbname=postgres
pgsql_player_connection = host=/var/run/postgresql user=postgres password=enter dbname=postgres

pgsql_mapserver_connection = host=postgres port=5432 user=postgres password=enter dbname=mapserver

auth_backend = postgresql
mod_storage_backend = sqlite3
```

The postgres db is connected via sockets in the container: https://github.com/pandorabox-io/pandorabox.io/blob/b9308d0ec2bf5056634da8dbbc946f93ce262ae4/docker-compose.yml#L44-L55

Tcp sockets should work too though (this is even tested here in the `mtdb` package: https://github.com/minetest-go/mtdb/blob/138281246419a03804202ddbfd8ce65c319d6b32/.github/workflows/test.yml#L9-L17)

can you show me your `world.mt` file and/or the error message?

Also just fyi: this is a work-in-progress, thing might break on occasion :)

**Comment by nonfreegithub** [comment]
> can you show me your `world.mt` file and/or the error message?

I use not docker.

my world.mt:

```
backend = postgresql
gameid = MineClone2
creative_mode = false
enable_damage = true
player_backend = sqlite3
auth_backend = sqlite3
mod_storage_backend = sqlite3
server_announce = true
pgsql_connection = host=127.0.0.1 port=5432 user=user password=password dbname=minetest
pgsql_mapserver_connection = host=127.0.0.1 port=5432 user=user password=password dbname=mapserver
load_mod_mtui = mods/mtui_mod
```

my minetest.conf:

```
mtui.url = http://127.0.0.1:8080
mtui.key = my_key
```

my mtui_start.sh (systemd run this script):

`API_KEY=my_key SERVER_NAME=Server MINETEST_CONFIG=~/.minetest/minetest.conf ./mtui`

my error is that I can not connect to my user in mtui interface, not in my old main server with pgsql, but I can in my test sqlite server.

It return **login failed**

![Captura de pantalla de 2023-09-11 01-27-59](https://github.com/minetest-go/mtui/assets/122187904/be627cd7-d0fb-441b-a04b-f14a882c3766)

> Also just fyi: this is a work-in-progress, things might break on occasion :)

I know, good work!

**Comment by nonfreegithub** [comment]
I try using /mtui_tan in server, then in mtui web interface I try my game nick and my mtui_tan temp passwd, it still returning **login failed**

**Comment by nonfreegithub** [comment]
maybe it search about a pgsql auth backend but it's sqlite3

**Comment by nonfreegithub** [comment]
ok in new release v1.43 corner icon loads.

but I can not login

I try registering a new user in the mt server then login in mtui web interface but nope

Is something with auth backend I think

**Comment by BuckarooBanzay** [comment]
I'm not sure where (if?) i documented it, but the cookie is only valid on the host `127.0.0.1`, which url did you use to access it?

(an example to set a custom cookie domain: https://github.com/pandorabox-io/pandorabox.io/blob/c82f3d0cd5d3c42a238430294a916172f65af249/docker-compose.yml#L49-L51)
