### ISSUE TITLE
Mediaserver doc

### ISSUE THREAD

**Issue by nonfreegithub** [minetest-go/mtui#238]
How can I interact with my mt media server via mtui?

**Comment by BuckarooBanzay** [comment]
uhm, what do you mean? there is a builtin "remote media" server to serve media assets via http, the url should be visible on the "Mediaserver" page though :thinking:

**Comment by nonfreegithub** [comment]
So mtui, which is hosted on the same server as minetest server, provides the media to the client instead of being mt server? How useful could this functionality be? It does not reduce the load on the network/processor/RAM of the minetest server because it is hosted on the same machine.

I thought it was an interface to interact with some media server on another host

**Comment by BuckarooBanzay** [comment]
>  It does not reduce the load on the network/processor/RAM of the minetest server because it is hosted on the same machine.

Yeah, but it moves the load off the minetest (udp) protocol to a more efficient transfer protocol (at least for that type of media)

**Comment by nonfreegithub** [comment]
yes it's right
