### ISSUE TITLE
Banned players can chat in server with a mtui chat session

### ISSUE THREAD

**Issue by nonfreegithub** [minetest-go/mtui#246]
mtui version 1.49

banned players can log in to mtui to access the chat

xban mod and xban integration mtui feature is enabled

maybe mtui could prevent xbanned players from logging in to mtui

It would also be nice to be able to disable the chat feature

**Comment by BuckarooBanzay** [comment]
> It would also be nice to be able to disable the chat feature

done :+1: 

> maybe mtui could prevent xbanned players from logging in to mtui

on login or session-refresh the on-disk xban db is checked (if enabled) it might have some delay up to 5 minutes until the engine writes the updated xban records back.
i don't want to query the server directly on every login, there is too much that can go wrong or get delayed.

Anyways, you didn't answer my question in another issue: what and how do you use the mtui?

**Comment by nonfreegithub** [comment]
> what and how do you use the mtui?

I try it in a little friends server
