### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by lotigara** [minetest-go/mtui#332]
How did you install this software? Are there any installation instructions or something similar?

P.S. Please don't suggest containers, I want to run mtui on my host machine, not the guest container.

**Comment by BuckarooBanzay** [comment]
there's no real setup manual yet, but in the meantime:

binary downloads are in the tar.gz file in the releases: https://github.com/minetest-go/mtui/releases/tag/v1.63

the executable is context-dependent and usually started with the world-directory as CWD/current directory

i _think_ the only mandatory environment variable is `API_KEY` which you have to set to a unique and secret value. The mtui mod part needs that key too (and the url to the ui of course)

post here if you have more questions, but just a reminder: this is still alpha-software, don't expect much

**Comment by lotigara** [comment]
Thanks! Maybe I'll write the instructions for an installation with services and reverse proxy.

**Comment by lotigara** [comment]
Hmm, when I'm proxying mtui via Nginx, mtui (not Nginx!) prints 404 error. Here are an Nginx site and a systemd service, both for mtui:
Systemd service:
```systemd
[Unit]
Description=Minetest web ui
After=network.target
RequiresMountsFor=/var/games/minetest-server

[Service]
Restart=on-failure
User=Debian-minetest
Group=games
Environment="SERVER_NAME=Lotigara MINETEST_CONFIG=/etc/minetest/minetest.conf"
WorkingDirectory=/var/games/minetest-server/.minetest/worlds/world
ExecStart=/usr/local/bin/mtui

[Install]
WantedBy=multi-user.target
```

Nginx site:
```nginx
server {
    location /minetest {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
```

**Comment by BuckarooBanzay** [comment]
> Hmm, when I'm proxying mtui via Nginx, mtui (not Nginx!*) prints 404 error. Here are an Nginx site and a systemd service, both for mtui:

I have a working example here, if that helps: https://github.com/pandorabox-io/pandorabox.io/blob/master/config/nginx.conf#L103-L111

**Comment by lotigara** [comment]
Thanks! I'll try this.

**Comment by lotigara** [comment]
I finally understood the problem! The reason was missing ***`/`*** characters in my Nginx config. There is a valid one:
`location /minetest`***`/`***` {`
`proxy_pass http://127.0.0.1:8080`***`/`***`;`

**Comment by lotigara** [comment]
And just note for viewers: both Nginx config and a systemd service are [above](https://github.com/minetest-go/mtui/issues/332#issuecomment-2132276882).
