### ISSUE TITLE
Mail?

### ISSUE THREAD

**Issue by MCLV-pandorabox** [minetest-go/mtui#51]
Nice new UI look
Lost the mail functionality for normal users like myself tho.
Not too happy about that. Probably oversight?
Looking forward to seeing that fixed soon.
![webui](https://user-images.githubusercontent.com/107920484/197417416-75d9adad-f3bd-4c45-bd4a-3b9b4aa2162a.png)

**Comment by MCLV-pandorabox** [comment]
Hmmmm.. it just got fixed. odd.

**Comment by BuckarooBanzay** [comment]
>  Not too happy about that. Probably oversight?

Yeah, there's a feature-list now, forgot to enable the mail part :) the app crashed a few hours ago though (and i forgot the `restart: always` part too :facepalm: https://github.com/pandorabox-io/pandorabox.io/commit/f0ccfa025ecb7ae454237fc20857b4e17c0f151a)
Should run again now :+1:
